//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.WEB.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.WEB.MVC.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Money Back.
        /// </summary>
        public static string _100_MoneyBack {
            get {
                return ResourceManager.GetString("100%MoneyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Secure Payment.
        /// </summary>
        public static string _100_SecurePayment {
            get {
                return ResourceManager.GetString("100%SecurePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 SUPPORT.
        /// </summary>
        public static string _24_7SUPPORT {
            get {
                return ResourceManager.GetString("24/7SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressMain {
            get {
                return ResourceManager.GetString("AddressMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddtoCart {
            get {
                return ResourceManager.GetString("AddtoCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate.
        /// </summary>
        public static string Affiliate {
            get {
                return ResourceManager.GetString("Affiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string AvailabilityStatus {
            get {
                return ResourceManager.GetString("AvailabilityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becoming a leading economic corporation of Vietnam, operating in multiple industries, globally, bringing the highest added value to shareholders, partners, employees and society..
        /// </summary>
        public static string Becomingaleadingeconomiccorporationof_Vietnam {
            get {
                return ResourceManager.GetString("Becomingaleadingeconomiccorporationof Vietnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becoming a multi-industry economic group, the company&apos;s asset value and brand name are among the largest non-state enterprises in Vietnam..
        /// </summary>
        public static string Becomingamultiindustryeconomicgroupthecompanysasset {
            get {
                return ResourceManager.GetString("Becomingamultiindustryeconomicgroupthecompanysasset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Shipping.
        /// </summary>
        public static string CalculateShipping {
            get {
                return ResourceManager.GetString("CalculateShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us now.
        /// </summary>
        public static string CallNow {
            get {
                return ResourceManager.GetString("CallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Summary.
        /// </summary>
        public static string CartSummary {
            get {
                return ResourceManager.GetString("CartSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Total.
        /// </summary>
        public static string CartTotal {
            get {
                return ResourceManager.GetString("CartTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CATEGORIES {
            get {
                return ResourceManager.GetString("CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit to quality products.
        /// </summary>
        public static string Committoqualityproducts {
            get {
                return ResourceManager.GetString("Committoqualityproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company operations.
        /// </summary>
        public static string CompanyOperations {
            get {
                return ResourceManager.GetString("CompanyOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us 24 hrs a day.
        /// </summary>
        public static string ContactUs24hrsADay {
            get {
                return ResourceManager.GetString("ContactUs24hrsADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create orders online quickly.
        /// </summary>
        public static string Createordersonlinequickly {
            get {
                return ResourceManager.GetString("Createordersonlinequickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer refund policy.
        /// </summary>
        public static string Customerrefundpolicy {
            get {
                return ResourceManager.GetString("Customerrefundpolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Support.
        /// </summary>
        public static string CustomerSupport {
            get {
                return ResourceManager.GetString("CustomerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Customer support .
        /// </summary>
        public static string Customersupport247 {
            get {
                return ResourceManager.GetString("Customersupport247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Information.
        /// </summary>
        public static string DeliveryInformation {
            get {
                return ResourceManager.GetString("DeliveryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dong Nguyen Xanh.
        /// </summary>
        public static string DongNguyenXanh {
            get {
                return ResourceManager.GetString("DongNguyenXanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dongnguyenxanh will be a place to meet all the needs of customers in terms of product variety, quality and reasonable prices. Dongnguyenxanh will always try our best to innovate to constantly improve the quality of our products in response to our customers&apos; trust..
        /// </summary>
        public static string DongnguyenxanhWillBeAPlaceToMeetAllTheNeedsOfCustomers {
            get {
                return ResourceManager.GetString("DongnguyenxanhWillBeAPlaceToMeetAllTheNeedsOfCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EASY ORDER .
        /// </summary>
        public static string EASYORDER {
            get {
                return ResourceManager.GetString("EASYORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure customer information security.
        /// </summary>
        public static string Ensurecustomerinformationsecurity {
            get {
                return ResourceManager.GetString("Ensurecustomerinformationsecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email  address here .
        /// </summary>
        public static string EnterYourEmailAddressHere {
            get {
                return ResourceManager.GetString("EnterYourEmailAddressHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAST DELIVERY.
        /// </summary>
        public static string FASTDELIVERY {
            get {
                return ResourceManager.GetString("FASTDELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE RETURN.
        /// </summary>
        public static string FREERETURN {
            get {
                return ResourceManager.GetString("FREERETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping.
        /// </summary>
        public static string FreeShipping {
            get {
                return ResourceManager.GetString("FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping On Order.
        /// </summary>
        public static string FreeShippingOnOrder {
            get {
                return ResourceManager.GetString("FreeShippingOnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Certificates.
        /// </summary>
        public static string GiftCertificates {
            get {
                return ResourceManager.GetString("GiftCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee.
        /// </summary>
        public static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline.
        /// </summary>
        public static string Hotline {
            get {
                return ResourceManager.GetString("Hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to improve product quality and better service quality, Dongnguyenxanh is looking forward to the support and comments from our customers..
        /// </summary>
        public static string Inordertoimproveproductqualityandbetterservicequality {
            get {
                return ResourceManager.GetString("Inordertoimproveproductqualityandbetterservicequality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest blogs.
        /// </summary>
        public static string LatestBlogs {
            get {
                return ResourceManager.GetString("LatestBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product of category.
        /// </summary>
        public static string ListProductCategories {
            get {
                return ResourceManager.GetString("ListProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Price.
        /// </summary>
        public static string LowestPrice {
            get {
                return ResourceManager.GetString("LowestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY BACK GUARNTEE.
        /// </summary>
        public static string MONEYBACKGUARNTEE {
            get {
                return ResourceManager.GetString("MONEYBACKGUARNTEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help.
        /// </summary>
        public static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment secure.
        /// </summary>
        public static string NewProducts {
            get {
                return ResourceManager.GetString("NewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR GOAL.
        /// </summary>
        public static string OURGOAL {
            get {
                return ResourceManager.GetString("OURGOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MISSION.
        /// </summary>
        public static string OURMISSION {
            get {
                return ResourceManager.GetString("OURMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VISSION.
        /// </summary>
        public static string OURVISSION {
            get {
                return ResourceManager.GetString("OURVISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán an toàn.
        /// </summary>
        public static string PaymentSecure {
            get {
                return ResourceManager.GetString("PaymentSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone no.
        /// </summary>
        public static string Phoneno {
            get {
                return ResourceManager.GetString("Phoneno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        public static string Placeorder {
            get {
                return ResourceManager.GetString("Placeorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular products.
        /// </summary>
        public static string PopularProducts {
            get {
                return ResourceManager.GetString("PopularProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestigious products.
        /// </summary>
        public static string Prestigiousproducts {
            get {
                return ResourceManager.GetString("Prestigiousproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string PriceValue {
            get {
                return ResourceManager.GetString("PriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing dongnguyenxanh brand products of international quality, reasonable prices, satisfying customer needs, contributing to the development of the country..
        /// </summary>
        public static string Providingdongnguyenxanhbrandproductsofinternationalquality {
            get {
                return ResourceManager.GetString("Providingdongnguyenxanhbrandproductsofinternationalquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUALITY PRODUCT.
        /// </summary>
        public static string QUALITYPRODUCT {
            get {
                return ResourceManager.GetString("QUALITYPRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick delivery after customers place an order.
        /// </summary>
        public static string Quickdeliveryaftercustomersplaceanorder {
            get {
                return ResourceManager.GetString("Quickdeliveryaftercustomersplaceanorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund when the product is not qualified.
        /// </summary>
        public static string Refundwhentheproductisnotqualified {
            get {
                return ResourceManager.GetString("Refundwhentheproductisnotqualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related posts.
        /// </summary>
        public static string RELATEDPOSTS {
            get {
                return ResourceManager.GetString("RELATEDPOSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search entire product here.
        /// </summary>
        public static string SearchEntireProductHere {
            get {
                return ResourceManager.GetString("SearchEntireProductHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECURE PAYMENT.
        /// </summary>
        public static string SECUREPAYMENT {
            get {
                return ResourceManager.GetString("SECUREPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this product.
        /// </summary>
        public static string Sharethisproduct {
            get {
                return ResourceManager.GetString("Sharethisproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ships Today.
        /// </summary>
        public static string ShipsToday {
            get {
                return ResourceManager.GetString("ShipsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Now.
        /// </summary>
        public static string ShoppingNow {
            get {
                return ResourceManager.GetString("ShoppingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        public static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcribe.
        /// </summary>
        public static string Subcribe {
            get {
                return ResourceManager.GetString("Subcribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe newsletter to get updated.
        /// </summary>
        public static string SubscribeNewsletterToGetUpdated {
            get {
                return ResourceManager.GetString("SubscribeNewsletterToGetUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-total.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support24/7.
        /// </summary>
        public static string Support24_7 {
            get {
                return ResourceManager.GetString("Support24/7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Us Your Message.
        /// </summary>
        public static string TellUsYourMessage {
            get {
                return ResourceManager.GetString("TellUsYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string Terms_Conditions {
            get {
                return ResourceManager.GetString("Terms&Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time now.
        /// </summary>
        public static string Timenow {
            get {
                return ResourceManager.GetString("Timenow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dong Nguyen Xanh Company.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top service.
        /// </summary>
        public static string Topservice {
            get {
                return ResourceManager.GetString("Topservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        public static string ViewCart {
            get {
                return ResourceManager.GetString("ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO.
        /// </summary>
        public static string WELCOMETO {
            get {
                return ResourceManager.GetString("WELCOMETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We really appreciate your purchase choices. Always committed to top quality reputation.
        /// </summary>
        public static string WeReallyAppreciateYourPurchaseChoicesAlwaysCommittedToTopQualityReputation {
            get {
                return ResourceManager.GetString("WeReallyAppreciateYourPurchaseChoicesAlwaysCommittedToTopQualityReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll never share your email address with a third-party..
        /// </summary>
        public static string WeWillNeverShareYourEmailAddressWithAThirdparty {
            get {
                return ResourceManager.GetString("WeWillNeverShareYourEmailAddressWithAThirdparty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN BEST ONLINE SHOP AT.
        /// </summary>
        public static string WINBESTONLINESHOPAT {
            get {
                return ResourceManager.GetString("WINBESTONLINESHOPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 30 Days To Return.
        /// </summary>
        public static string YouHave30DaysToReturn {
            get {
                return ResourceManager.GetString("YouHave30DaysToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
